---
remote: origin
target-branch: main
helm-extra-args: --timeout 600s
chart-dirs:
  - charts
excluded-charts:
  - charts/common
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
  - k8s-at-home=https://k8s-at-home.com/charts
  - zbytes=https://zbytes.github.io/helm-charts
